update with some notes and comments

diff --git a/scripts/gitcheck b/scripts/gitcheck
--- a/scripts/gitcheck
+++ b/scripts/gitcheck
@@ -10,6 +10,7 @@
 # add alittle color for the cd break it up alittle better
 # run on directories that contain directories that are git repos 
 # for i in *; do cd $i; git status; echo ""; cd ..;done 
+# Format the output look at print the pwd, status or pull together colored and with proper spacing 
 
 black=$'\e[30m'
 red=$'\e[31m'
@@ -24,7 +25,7 @@ reset=$'\e[0m'
 gitrun(){
     local input=$1
     for i in *; do 
-        cd "$i" || { echo "cd failed"; exit 1; }
+        cd "$i" || { echo "cd failed"; exit 1; } # Should check and fail against a none dir
         git "$input"
         echo ""
         cd ..
